[alias]
xtask = "run --package xtask --"

[build]
rustflags = ["-Wunused-crate-dependencies"]
incremental = true

# Reduce memory usage for ARM v7 build
[profile.release]
lto = false
codegen-units = 32
opt-level = 1
strip = true